import crawlerWithList from './crawler/crawlerWithList'

const list = [
  // 'David Cross',
  // 'Eddie Griffin',
  // 'George Carlin',
  // 'Richard Pryor',
  // 'Chris Rock',
  // 'Eddie Murphy',
  // 'Robin Williams',
  // 'Ellen DeGeneres',
  // 'Bill Hicks',
  // 'Jon Stewart',
  // 'Joan Rivers',
  // 'Adam Sandler',
  // 'Sarah Silverman',
  // 'Kevin Hart',
  // 'Whitney Cummings',
  // 'Jeffrey Ross',
  // 'Russell Peters',
  // 'Doug Benson',
  // 'Matt Rife',
  // 'Ashley Gavin',
  // 'Mike Vecchione',
  // 'Drew Lynch',
  // 'Marc Maron',
  // 'Jimmy O. Yang',
  // 'Daniel Sloss',
  // 'Trevor Noah',
  // 'Ricky Gervais',
  // 'Jim Gaffigan',
  // 'Pete Davidson',
  // 'Sam Morril',
  // 'Roy Wood Jr.',
  // 'Jeff Dunham',
  // 'Gabriel lglesias',
  // 'Ali Wong',
  // 'Russell Howard',
  // 'Jim Jefferies',
  // 'John Olivers',
  // 'Lewis Black',
  // 'Ashley Gavin',
  // 'Drew Lynch',
  // 'Daniel Sloss',
  // 'Sam Morril'
  // 'Jeff Dunham'
  'Mike Vecchione',
  'John Olivers'
]

crawlerWithList(list)